"""Campo asignado

Revision ID: 028178cc52d7
Revises: edc9e2d0a274
Create Date: 2023-06-08 06:23:48.951293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '028178cc52d7'
down_revision = 'edc9e2d0a274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OBTEmpleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Asignado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('OBTPuesto', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=4294000000),
               existing_nullable=True)

    with op.batch_alter_table('OBTResponsable', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=4294000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OBTResponsable', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.String(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('OBTPuesto', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.String(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('OBTEmpleado', schema=None) as batch_op:
        batch_op.drop_column('Asignado')

    # ### end Alembic commands ###
