"""empty message

Revision ID: 6f899cbee3c2
Revises: 
Create Date: 2023-06-06 22:50:45.129445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f899cbee3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OBTEmpleado',
    sa.Column('IdEmpleado', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=512), nullable=False),
    sa.Column('Apellido', sa.String(length=512), nullable=False),
    sa.Column('Telefono', sa.String(length=20), nullable=True),
    sa.Column('DPI', sa.String(length=13), nullable=False),
    sa.Column('Email', sa.String(length=512), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('IdPuesto', sa.Integer(), nullable=True),
    sa.Column('UsuarioCreo', sa.String(length=255), nullable=True),
    sa.Column('UsuarioModifico', sa.String(length=255), nullable=True),
    sa.Column('FechaCreo', sa.DateTime(), nullable=True),
    sa.Column('FechaModifico', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('IdEmpleado')
    )
    op.create_table('OBTPuesto',
    sa.Column('IdPuesto', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=512), nullable=False),
    sa.Column('Descripcion', sa.String(length=4294000000), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('UsuarioCreo', sa.String(length=255), nullable=True),
    sa.Column('UsuarioModifico', sa.String(length=255), nullable=True),
    sa.Column('FechaCreo', sa.DateTime(), nullable=True),
    sa.Column('FechaModifico', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('IdPuesto')
    )
    op.create_table('OBTRequerimiento',
    sa.Column('IdRequerimiento', sa.Integer(), nullable=False),
    sa.Column('Descripcion', sa.String(length=512), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('Estandar', sa.Boolean(), nullable=True),
    sa.Column('UsuarioCreo', sa.String(length=255), nullable=True),
    sa.Column('UsuarioModifico', sa.String(length=255), nullable=True),
    sa.Column('FechaCreo', sa.DateTime(), nullable=True),
    sa.Column('FechaModifico', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('IdRequerimiento')
    )
    op.create_table('OBTRequerimientoEmpleado',
    sa.Column('IdRequerimientoEmpleado', sa.Integer(), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('Completado', sa.Boolean(), nullable=True),
    sa.Column('FechaCompletado', sa.DateTime(), nullable=True),
    sa.Column('IdEmpleado', sa.Integer(), nullable=True),
    sa.Column('IdRequerimiento', sa.Integer(), nullable=True),
    sa.Column('UsuarioCreo', sa.String(length=255), nullable=True),
    sa.Column('UsuarioModifico', sa.String(length=255), nullable=True),
    sa.Column('FechaCreo', sa.DateTime(), nullable=True),
    sa.Column('FechaModifico', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('IdRequerimientoEmpleado')
    )
    op.create_table('OBTResponsable',
    sa.Column('IdResponsable', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=512), nullable=False),
    sa.Column('Email', sa.String(length=512), nullable=False),
    sa.Column('Descripcion', sa.String(length=4294000000), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('UsuarioCreo', sa.String(length=255), nullable=True),
    sa.Column('UsuarioModifico', sa.String(length=255), nullable=True),
    sa.Column('FechaCreo', sa.DateTime(), nullable=True),
    sa.Column('FechaModifico', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('IdResponsable')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OBTResponsable')
    op.drop_table('OBTRequerimientoEmpleado')
    op.drop_table('OBTRequerimiento')
    op.drop_table('OBTPuesto')
    op.drop_table('OBTEmpleado')
    # ### end Alembic commands ###
