"""Relaciones

Revision ID: edc9e2d0a274
Revises: 6f899cbee3c2
Create Date: 2023-06-07 14:50:37.360362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edc9e2d0a274'
down_revision = '6f899cbee3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OBTPuesto', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=4294000000),
               existing_nullable=True)

    with op.batch_alter_table('OBTRequerimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IdPuesto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('IdResponsable', sa.Integer(), nullable=True))

    with op.batch_alter_table('OBTResponsable', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=4294000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OBTResponsable', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.String(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('OBTRequerimiento', schema=None) as batch_op:
        batch_op.drop_column('IdResponsable')
        batch_op.drop_column('IdPuesto')

    with op.batch_alter_table('OBTPuesto', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.String(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
